### ISSUE TITLE
St Jude Prize Draw

### ISSUE THREAD

**Issue by mishmanners** [mishmanners/stjude23-raffle#1]
## Prize

Everyone knows I [somehow manage to accumulate a lot of GitHub merch](https://twitter.com/github/status/1651996600380665856), well now I'm giving away a special, highly coveted GitHub piece of merch, that not many people around the world have... a sublimated GitHub blanket:

![20230505_154225](https://user-images.githubusercontent.com/36594527/236385198-0cd7ca7e-fac0-452d-a6ab-9823aa72b1d8.jpg)

ONLY 50 of these were made in the whole world! You'll receive a brand new blanket in the package.

You'll also get a bunch of stickers!

## St Jude PLAY LIVE fundraising campaign

I'm raising money for [St Jude Children's Research hospital](https://www.stjude.org/) that helps kids and their families with cancer. The hospital also conducts research to cure cancer, and shares that with the world 🙌  To help us on our fundraising journey, this year I wanted to do a slightly more offline fundraiser. I raise money on my [Twitch live streams](https://twitch.tv/MishManners) but not everyone can tune in at that time.

So here's a way for you to raise money for St Jude with me during the campaign, and win yourself an epic GitHub prize. The blanket will also come with lots of stickers! And maybe some sneaky other pieces of GitHub merch.

It's really easy to enter the prize draw:
1. Donate to my [St Jude PLAY LIVE](https://donate.tiltify.com/@mishmanners/mishmannersplaylive23) campaign.
2. Submit a comment on the issue 👇 

## Double the donation

If your employer matches donations (for example, GitHub or Microsoft), once you're at the end of the donation screen, you can select to "employer Match" your donation and log in through your company portal and your donation will be automatically matched!

## How the Prize draw works

Anyone who donates even $1 will be entered into the prize draw! Get your donations in by the end of May PT. I'll be doing the prize draw (using GitHub Actions) live on stream during the our St Jude celebration. You don't need to be present to win the prize. Once the winner is randomly selected (via GitHub Actions), I'll immediately verify that the selected person has given a donation to my [St Jude PLAY LIVE](https://donate.tiltify.com/@mishmanners/mishmannersplaylive23) campaign.

If the selected person has made a donation, they'll win the prize. I'll contact the winner to ship the prize pack direct to them. If the selected person has not made a donation, they will not win the prize, and instead a redraw will immediately take place until an eligible participant is selected.

If you want to enter the draw you'll need to make sure you donate under your name. If your name is different than your GitHub handle, you can write that in the comments.

Good luck! And let's raise money for St Jude!

**Comment by billythekid** [comment]
w00t w00t, love me some swag. donated $5 🤞 

Thanks for doing this!

Noting for others that I found the employer match via that site has a minimum match of $25 for GitHub but you don't find out until after donating. I was still able to match it via Spark Benevity:

https://github.benevity.org/request-a-match?cause_id=840-620646012

**Comment by stacycarter** [comment]
Yaaas, more GitHub swag! That GitHub blanket is very nice and this is a great fundraiser. Donated and crossing my fingers 🤞

**Comment by davebunte** [comment]
Donated :heart:

**Comment by lesley** [comment]
Awesome! Donated!

**Comment by nolecram** [comment]
Donated and matched using the internal link... https://github.benevity.org/request-a-match?cause_id=840-620646012
On the Tiltify website I got stuck....

Anyway Fantastic Initiative ❤️

**Comment by dylan-mccarthy** [comment]
Donated :)

**Comment by febuiles** [comment]
Thanks for running this Mish, mheroin ❤️ blankets!

**Comment by thatinstaxguy** [comment]
Thank you for running this Mish! Blankies!

**Comment by mishmanners** [comment]
Thank you everyone for entering the prize draw.

**Comment by mishmanners** [comment]
Thank you everyone for entering the prize draw ❤️

**Comment by mishmanners** [comment]
Thank you everyone for entering the prize draw ❤️

**Comment by mishmanners** [comment]
Thank you everyone for entering the prize draw ❤️

**Comment by mishmanners** [comment]
After spending some time on stream, and fixing some of the code, we ran the raffle. Congrats to @davebunte for winning the prize! DM me so I can ship your amazing blanket. Thanks again everyone for being part of the St Jude PLAY LIVE campaign.
